proyecto:
    path:     /
    defaults: { _controller: "IntranetBundle:Proyecto:index" }

proyecto_show:
    path:     /{id}/show
    defaults: { _controller: "IntranetBundle:Proyecto:show" }

proyecto_new:
    path:     /new
    defaults: { _controller: "IntranetBundle:Proyecto:new" }

proyecto_create:
    path:     /create
    defaults: { _controller: "IntranetBundle:Proyecto:create" }
    methods:  POST

proyecto_edit:
    path:     /{id}/edit
    defaults: { _controller: "IntranetBundle:Proyecto:edit" }

proyecto_update:
    path:     /{id}/update
    defaults: { _controller: "IntranetBundle:Proyecto:update" }
    methods:  [POST, PUT]

proyecto_delete:
    path:     /{id}/delete
    defaults: { _controller: "IntranetBundle:Proyecto:delete" }
    methods:  [POST, DELETE]
